version: '3.8'
services:
  nginx-certbot:
    image: jonasal/nginx-certbot:latest
    volumes:
      - ./volumes/startup:/startup
      - ./volumes/secrets:/secrets
      - ./volumes/config:/etc/nginx/user_conf.d
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./secrets.env
    command: /bin/sh -c 'chmod +x /startup/startup.sh; /startup/startup.sh'
  bps-fastapi:
    build: ../
    volumes:
      - ./volumes/data:/code/data
    ports:
      - 8080:8080
    environment:
      - ENV=production

